# Generated by Django 5.1.4 on 2025-02-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paragraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
