# Generated by Django 5.1.4 on 2025-02-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileB', models.FileField(upload_to='ProfileFiles/Bin')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('postUserB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_files', to='api.profile')),
            ],
        ),
    ]
